[versions]
sonar-commons = "2.21.0.4626"
# Before updating the plugin-api version, make sure to check the compatibility matrix and stick to the lowest denominator
# https://github.com/SonarSource/sonar-plugin-api?tab=readme-ov-file#compatibility
sonar-plugin-api = "13.4.3.4290"
sonarqube = "26.2.0.119303"
sonar-orchestrator = "6.1.0.3962"
sonarlint = "10.45.0.84373"
sslr = "1.25.1.3886"
junit = "6.0.3"
assertj = "3.27.7"
mockito = "5.22.0"
jsr305 = "3.0.2"
staxmate = "2.0.1"
awaitility = "4.3.0"
woodstox = "7.1.1"
ch-qos-logback-logback = "1.5.32"

[libraries]
sonar-analyzer-commons = { module = "org.sonarsource.analyzer-commons:sonar-analyzer-commons", version.ref = "sonar-commons" }
sonar-analyzer-test-commons = { module = "org.sonarsource.analyzer-commons:sonar-analyzer-test-commons", version.ref = "sonar-commons" }
sonar-regex-parsing = { module = "org.sonarsource.analyzer-commons:sonar-regex-parsing", version.ref = "sonar-commons" }
sonar-plugin-api = { module = "org.sonarsource.api.plugin:sonar-plugin-api", version.ref = "sonar-plugin-api" }
sonar-plugin-api-impl = { module = "org.sonarsource.sonarqube:sonar-plugin-api-impl", version.ref = "sonarqube" }
sonar-plugin-api-test-fixtures = { module = "org.sonarsource.api.plugin:sonar-plugin-api-test-fixtures", version.ref = "sonar-plugin-api" }
sonar-testing-harness = { module = "org.sonarsource.sonarqube:sonar-testing-harness", version.ref = "sonarqube" }
sonar-ws = { module = "org.sonarsource.sonarqube:sonar-ws", version.ref = "sonarqube" }
sonar-orchestrator-junit5 = { module = "org.sonarsource.orchestrator:sonar-orchestrator-junit5", version.ref = "sonar-orchestrator" }
sonar-lint-core = { module = "org.sonarsource.sonarlint.core:sonarlint-core", version.ref = "sonarlint" }
sonar-lint-rpc-java-client = { module = "org.sonarsource.sonarlint.core:sonarlint-rpc-java-client", version.ref = "sonarlint" }
sonar-lint-rpc-impl = { module = "org.sonarsource.sonarlint.core:sonarlint-rpc-impl", version.ref = "sonarlint" }
sslr-core = { module = "org.sonarsource.sslr:sslr-core", version.ref = "sslr" }
sslr-testing-harness = { module = "org.sonarsource.sslr:sslr-testing-harness", version.ref = "sslr" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
# Version of JUnit Platform is taken from the JUnit BOM that is imported by junit-jupiter
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox" }
staxmate = { module = "org.codehaus.staxmate:staxmate", version.ref = "staxmate" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback-logback" }
