name: bump-versions
on:
  workflow_call:
    inputs:
      version:
        description: The new version
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: The new version
        required: true
        type: string

jobs:
  bump-version:
    runs-on: github-ubuntu-latest-s
    permissions:
      contents: write # write for peter-evans/create-pull-request, read for actions/checkout
      pull-requests: write # write for peter-evans/create-pull-request
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - env:
          VERSION: ${{ inputs.version }}
        run: |
          sed -i "s/version=.*/version=$VERSION/" gradle.properties
          cd php-custom-rules-plugin/maven && mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$VERSION
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          author: ${{ github.actor }} <${{ github.actor }}>
          commit-message: Prepare next development iteration
          title: Prepare next development iteration
          branch: bot/bump-project-version
          branch-suffix: timestamp
          base: master
          reviewers: ${{ github.actor }}
